name: Pages

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
      - name: Upload to qiniu
        uses: saltbo/uptoc@v1.4.3
        with:
          driver: qiniu
          region: cn-south-1
          bucket: ray-blog
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QINIU_AK }}
          UPTOC_UPLOADER_SK: ${{ secrets.QINIU_SK }}
      - name: Refresh Qiniu CDN
        run: bash depoly.sh ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }}